version: '3'
services:
    server:
        container_name: stylify
        build: docker/server
        working_dir: /usr/share/nginx/html
        volumes:
            - ./.:/usr/share/nginx/html:delegated
        ports:
            - 82:80
            - 81:81 # Stylify nuxt module playground
        tty: true
