name: Tests

on:
    push:
        branches:
        - '**'
    pull_request:
        branches:
        - main

jobs:
  tests:
    name: Tests build
    runs-on: ubuntu-latest

    steps:
        - uses: actions/checkout@v3

        - uses: pnpm/action-setup@v2

        - uses: actions/setup-node@v3
          with:
            node-version: 18
            cache: pnpm

        - name: Versions
          run: node -v && pnpm -v

        - name: Install packages
          run: pnpm repo:init

        - name: Build
          run: pnpm build

        - name: Eslint
          run: pnpm eslint:check

        - name: Jest tests
          run: pnpm jest:test+coverage

        - name: 'Upload Artifacts'
          if: ${{ failure() }}
          uses: actions/upload-artifact@v3
          with:
            name: artifacts
            path: |
              packages
              !node_modules
              !packages/*/**/node_modules

        - name: Upload coverage to Codecov
          uses: codecov/codecov-action@v1
          with:
            token: ${{ secrets.CODECOV_TOKEN }}
