name: Tests

on:
    push:
        branches:
            - '*'
    pull_request:
        branches-ignore:
            - master

jobs:
    tests-windows:
        name: Tests - Windows
        runs-on: windows-latest

        steps:
            - uses: actions/checkout@v3

            - uses: pnpm/action-setup@v2

            - uses: actions/setup-node@v3
              with:
                  node-version: 16
                  cache: pnpm

            - name: Install packages
              run: pnpm repo:init

            - name: Build
              run: pnpm build

            - name: Jest tests
              run: pnpm stylify:test && pnpm bundler:test
